version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test_windows:
    executor: windows/default
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - run: setx GOPATH %USERPROFILE%\go
      - run: go get gotest.tools/gotestsum
      - run: mkdir test_results
      - run: setx TESTING "true"

      - run:
          name: Run tests
          command: |
            C:\Users\circleci\go\bin\gotestsum.exe --junitfile test_results/windows.xml
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  ci:
    jobs:
      - test_windows
